apiVersion: v1
kind: Secret
metadata:
  name: fraud-pipeline-secrets
  namespace: airflow
type: Opaque
stringData:
  POSTGRES_PASSWORD: "fraud_pass"
  MINIO_ACCESS_KEY: "fraud_minio_user"
  MINIO_SECRET_KEY: "fraud_minio_pass"
