apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: fraud
  namespace: fraud-infra
spec:
  predictor:
    containers:
    - name: kserve-container
      image: ancaotrinh/fraud-inference:v1
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
        protocol: TCP
      readinessProbe:
        httpGet:
          path: /v2/health/ready
          port: 8080
        initialDelaySeconds: 30
        periodSeconds: 10
        failureThreshold: 10
      livenessProbe:
        httpGet:
          path: /v2/health/live
          port: 8080
        initialDelaySeconds: 60
        periodSeconds: 30
      env:
      - name: POSTGRES_PASSWORD
        value: "fraud_pass"
      - name: MINIO_ACCESS_KEY
        value: "fraud_minio_user"
      - name: MINIO_SECRET_KEY
        value: "fraud_minio_pass"
      resources:
        requests:
          cpu: "500m"
          memory: "512Mi"
        limits:
          cpu: "1"
          memory: "1Gi"
