apiVersion: v1
kind: Secret
metadata:
  name: fraud-pipeline-secret
  namespace: fraud-infra
type: Opaque
stringData:
  POSTGRES_PASSWORD: "fraud_pass"
  MINIO_ACCESS_KEY: "fraud_minio_user"
  MINIO_SECRET_KEY: "fraud_minio_pass"
  DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1512885679514849473/-cUfoZM6M3-qa8jm7XdgasxXT66ZAEp5dEKpzMy2biqKZrIw0iKxOp00OKDoxSUmHaoe"     # paste your Discord webhook URL here
---
apiVersion: v1
kind: Secret
metadata:
  name: fraud-pipeline-secrets
  namespace: airflow
type: Opaque
stringData:
  POSTGRES_PASSWORD: "fraud_pass"
  MINIO_ACCESS_KEY: "fraud_minio_user"
  MINIO_SECRET_KEY: "fraud_minio_pass"
  DISCORD_WEBHOOK_URL: ""     # paste your Discord webhook URL here
