apiVersion: v1
kind: Service
metadata:
  name: fraud-inference-metrics
  namespace: fraud-infra
  labels:
    app: fraud-inference
spec:
  selector:
    serving.knative.dev/service: fraud-predictor
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fraud-inference
  namespace: monitoring
  labels:
    release: kube-prom
spec:
  namespaceSelector:
    matchNames:
    - fraud-infra
  selector:
    matchLabels:
      app: fraud-inference
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
